import * as vscode from 'vscode';
import { sendAndRecord, SendRequest, Services } from '../services';
import { OutgoingMessage } from '../types';
import { BANNER, protectionOf, renderHtml, webviewOptions } from '../webview/html';

type FromWebview = { type: 'ready' } | { type: 'send'; message: OutgoingMessage };

const BODY = `
${BANNER}
<h2 id="target"></h2>
<p id="origin" class="muted"></p>
<form id="form">
  <div class="grid">
    <label>Content type <input id="contentType" type="text"></label>
    <label>Subject <input id="subject" type="text"></label>
    <label>Message ID <input id="messageId" type="text" placeholder="generated by Service Bus if empty"></label>
    <label>Correlation ID <input id="correlationId" type="text"></label>
    <label>Session ID <input id="sessionId" type="text" placeholder="required for session-enabled entities"></label>
  </div>
  <label>Application properties (JSON object) <textarea id="applicationProperties" rows="4" spellcheck="false"></textarea></label>
  <label>Body <textarea id="body" rows="14" spellcheck="false"></textarea></label>
  <div class="toolbar">
    <button id="send" type="submit" class="write">Send</button>
    <button id="format" type="button" class="secondary">Format JSON</button>
    <span id="status" class="status"></span>
  </div>
</form>`;

/** Compose form. Every send, successful or failed, goes through sendAndRecord and lands in the history. */
export class SendPanel {
  /** Blank compose forms, one per connection and target. Resends are not tracked: each one opens its own panel. */
  private static readonly open = new Map<string, SendPanel>();

  static show(services: Services, extensionUri: vscode.Uri, request: SendRequest): void {
    if (request.kind !== 'send') {
      new SendPanel(services, extensionUri, request);
      return;
    }
    // Reusing the panel keeps whatever draft is in it; a resend would have to overwrite it.
    const key = `${request.connection.id}/${request.queue}`;
    const existing = SendPanel.open.get(key);
    if (existing) {
      existing.panel.reveal();
      return;
    }
    SendPanel.open.set(key, new SendPanel(services, extensionUri, request, key));
  }

  private readonly panel: vscode.WebviewPanel;

  private constructor(
    private readonly services: Services,
    extensionUri: vscode.Uri,
    private readonly request: SendRequest,
    key?: string,
  ) {
    const verb = request.kind === 'resend' ? 'Resend to' : 'Send to';
    this.panel = vscode.window.createWebviewPanel(
      'sbw.send',
      `${verb} ${request.queue}`,
      vscode.ViewColumn.Active,
      webviewOptions(extensionUri),
    );
    this.panel.webview.html = renderHtml(this.panel.webview, extensionUri, 'send.js', BODY);
    this.panel.webview.onDidReceiveMessage((m: FromWebview) => this.handle(m));
    const protection = services.connections.onDidChange(() => this.post({ type: 'protection', ...this.protection }));
    this.panel.onDidDispose(() => {
      if (key) {
        SendPanel.open.delete(key);
      }
      protection.dispose();
    });
  }

  private get protection() {
    return protectionOf(this.services.connections.get(this.request.connection.id) ?? this.request.connection);
  }

  private async handle(message: FromWebview): Promise<void> {
    if (message.type === 'ready') {
      this.post({
        type: 'init',
        target: `${this.request.queue} · ${this.request.connection.name}`,
        origin: this.request.origin ? `Resending message from ${this.request.origin}` : '',
        message: this.request.message,
        ...this.protection,
      });
      return;
    }
    this.post({ type: 'busy', busy: true });
    try {
      await sendAndRecord(this.services, { ...this.request, message: message.message });
      // An empty body is valid in Service Bus, so it is sent; the note is there in case it was an oversight.
      const note = message.message.body === '' ? ' Note: the body was empty.' : '';
      this.post({ type: 'result', ok: true, text: `Sent at ${new Date().toLocaleTimeString()}. Saved to history.${note}` });
    } catch (err) {
      this.post({ type: 'result', ok: false, text: err instanceof Error ? err.message : String(err) });
    } finally {
      this.post({ type: 'busy', busy: false });
    }
  }

  private post(message: unknown): void {
    void this.panel.webview.postMessage(message);
  }
}
